export const socialIcons = {
  facebook: { name: 'Facebook', icon: ['fab', 'facebook'] },
  whatsapp: { name: 'WhatsApp', icon: ['fab', 'whatsapp'] },
  telegram: { name: 'Telegram', icon: ['fab', 'telegram'] },
  twitter: { name: 'Twitter/X', icon: ['fab', 'x-twitter'] },
  instagram: { name: 'Instagram', icon: ['fab', 'instagram'] },
  github: { name: 'GitHub', icon: ['fab', 'github'] },
  discord: { name: 'Discord', icon: ['fab', 'discord'] },
  youtube: { name: 'YouTube', icon: ['fab', 'youtube'] },
  pinterest: { name: 'Pinterest', icon: ['fab', 'pinterest'] },
  skype: { name: 'Skype', icon: ['fab', 'skype'] },
  gitlab: { name: 'GitLab', icon: ['fab', 'gitlab'] },
  twitch: { name: 'Twitch', icon: ['fab', 'twitch'] },
  threads: { name: 'Threads', icon: ['fab', 'threads'] },
  steam: { name: 'Steam', icon: ['fab', 'steam'] },
  reddit: { name: 'Reddit', icon: ['fab', 'reddit'] },
  linkedin: { name: 'LinkedIn', icon: ['fab', 'linkedin'] },
  'itch-io': { name: 'Itch.io', icon: ['fab', 'itch-io'] },
  mastodon: { name: 'Mastodon', icon: ['fab', 'mastodon'] },
  tiktok: { name: 'TikTok', icon: ['fab', 'tiktok'] },
  medium: { name: 'Medium', icon: ['fab', 'medium'] },
  vimeo: { name: 'Vimeo', icon: ['fab', 'vimeo'] },
  email: { name: 'E-mail', icon: ['fas', 'envelope'] },
  default: { name: 'Link', icon: ['fas', 'globe'] },
}

export type TSocialIcon = keyof typeof socialIcons
